repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo02
repo_name: 2024.2-Grupo02

# TODO - MUDAR A LOGO E FAVICON QUANDO DECIDIR O APP

site_name: Requisitos grupo 2
theme:
    name: material
    palette:
      - scheme: slate #slate = dark, default = light
        primary: green # cores - https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
        accent: amber
        toggle: 
            icon: material/brightness-4
            name: Modo escuro
        
      - scheme: default
        primary: green
        accent: amber
        toggle:
            icon: material/brightness-7
            name: Modo claro
        
    locale: pt_br
    logo: ./img/logo.jpeg # logo na barra de navegação do site
    favicon: ./img/logo.jpeg # logo na aba do navegador
    
    
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
